/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiiprograhotelutn.gui;

import proyectoiiprograhotelutn.gui.tiposhabitacion.FrmCargarTiposHabitacion;
import proyectoiiprograhotelutn.gui.puesto.FrmCargarPuestos;
import proyectoiiprograhotelutn.gui.agenciadeviajes.FrmCargarAgencias;
import proyectoiiprograhotelutn.gui.habitacion.FrmCargarHabitaciones;
import proyectoiiprograhotelutn.gui.usuario.FrmCargarUsuarios;

/**
 **
 ** @author Luis Alonso Corella Chaves
 ** 29/11/2017
 **/
public class FrmEliminar extends javax.swing.JFrame {
    /**
     * Creates new form FrmEliminar
     */
    public FrmEliminar() {
        initComponents();
        setLocationRelativeTo(null);
        btnRegresar.setContentAreaFilled(false);
    }
    private void irAModificarEliminarTipo(int opc){
        FrmCargarTiposHabitacion tipo = new FrmCargarTiposHabitacion(this, true, opc);
        tipo.setVisible(true);
    }
    public void irAModificarEliminarPuesto(int opc){
        FrmCargarPuestos puestos = new FrmCargarPuestos(this, true, opc);
        puestos.setVisible(true);  
    }
    public void irAModificarEliminarAgencia(int opc){
        FrmCargarAgencias agencias = new FrmCargarAgencias(this, true, opc);
        agencias.setVisible(true);  
    }
    public void irAModificarEliminarUsuario(int opc){
        FrmCargarUsuarios usuario = new FrmCargarUsuarios(this, true, opc);
        usuario.setVisible(true);  
    }
    public void irAModificarEliminarHabitacion(int opc){
        FrmCargarHabitaciones habitacion = new FrmCargarHabitaciones(this, true, opc);
        habitacion.setVisible(true);  
    }
    private void irAMenuPrincipal(){
        FrmMenuPrincipal principal = new FrmMenuPrincipal();
        principal.setVisible(true);
        dispose();
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTipoHabitacion = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblEliminar = new javax.swing.JLabel();
        btnPuesto = new javax.swing.JButton();
        btnAgencia = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnHabitaciones = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTipoHabitacion.setBackground(new java.awt.Color(204, 0, 0));
        btnTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnTipoHabitacion.setText("Tipo Habitación");
        btnTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 140, 30));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgAtras.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 10, 44, 28));

        lblEliminar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(204, 0, 0));
        lblEliminar.setText("Ventana para Eliminar");
        getContentPane().add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        btnPuesto.setBackground(new java.awt.Color(204, 0, 0));
        btnPuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnPuesto.setText("Puesto");
        btnPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuestoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 90, 30));

        btnAgencia.setBackground(new java.awt.Color(204, 0, 0));
        btnAgencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgencia.setForeground(new java.awt.Color(255, 255, 255));
        btnAgencia.setText("Agencia de Viajes");
        btnAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 140, 30));

        btnUsuario.setBackground(new java.awt.Color(204, 0, 0));
        btnUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setText("Usuarios");
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 90, 30));

        btnHabitaciones.setBackground(new java.awt.Color(204, 0, 0));
        btnHabitaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHabitaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnHabitaciones.setText("Habitaciones");
        btnHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnHabitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 140, 30));

        btnCliente.setBackground(new java.awt.Color(204, 0, 0));
        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 90, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgFondoRegistro.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoHabitacionActionPerformed
        irAModificarEliminarTipo(2);
    }//GEN-LAST:event_btnTipoHabitacionActionPerformed
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        irAMenuPrincipal();
    }//GEN-LAST:event_btnRegresarActionPerformed
    private void btnPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuestoActionPerformed
        irAModificarEliminarPuesto(2);
    }//GEN-LAST:event_btnPuestoActionPerformed
    private void btnAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenciaActionPerformed
        irAModificarEliminarAgencia(2);
    }//GEN-LAST:event_btnAgenciaActionPerformed
    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        irAModificarEliminarUsuario(2);
    }//GEN-LAST:event_btnUsuarioActionPerformed
    private void btnHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionesActionPerformed
        irAModificarEliminarHabitacion(2);
    }//GEN-LAST:event_btnHabitacionesActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEliminar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgencia;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnHabitaciones;
    private javax.swing.JButton btnPuesto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTipoHabitacion;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}