/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiiprograhotelutn.gui;
import proyectoiiprograhotelutn.bo.PuestoBO;
import proyectoiiprograhotelutn.entities.MiError;
import proyectoiiprograhotelutn.entities.Puesto;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** 28/11/2017
 **/
public class FrmPuesto extends javax.swing.JDialog {
    /**
     * Creates new form FrmTipoHabitacion
     */
    private Puesto puesto;
    public FrmPuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarPuesto.setContentAreaFilled(false);
        this.puesto = new Puesto();
        rdActivoPuesto.setVisible(false);
    }
    public FrmPuesto(java.awt.Frame parent, boolean modal, Puesto puesto) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarPuesto.setContentAreaFilled(false);
        btnRegistrarPuesto.setText("Editar");
        rdActivoPuesto.setContentAreaFilled(false);
        this.puesto = puesto;
        cargarPuesto();
    }
    private void irAFrmRegistro(){
        super.getParent().setVisible(true);
        dispose();
    } 
    public void registrarPuesto(){
        lblErrorPuesto.setText("");
        try {
            Puesto puestoNuevo = new Puesto();
            puestoNuevo.setId(this.puesto.getId());
            puestoNuevo.setNombre(txtNombrePuesto.getText().trim().toUpperCase());
            puestoNuevo.setDescripcion(txtDescripcionPuesto.getText().trim());
            if(!this.puesto.isActivo()){
                if(rdActivoPuesto.isSelected()){
                    puestoNuevo.setActivo(true);
                }else{
                    puestoNuevo.setActivo(false);
                }
            }
            PuestoBO puestobo = new PuestoBO();
            if (puestobo.registrarPuesto(puestoNuevo)) {
                lblErrorPuesto.setText("Puesto registrado con éxito.");
                super.getParent().setVisible(true);
                dispose();
            } else {
                lblErrorPuesto.setText("Intente nuevamente.");
            }
        } catch (MiError ex) {
            lblErrorPuesto.setText(ex.getMessage());
        } catch (Exception ex) {
            lblErrorPuesto.setText("Llamar a TI ...xD");
        }
    }
    public void cargarPuestos(){
        PuestoBO puestobo = new PuestoBO();
        for (int i = 0; i < puestobo.cargarPuestos().size(); i++) {
            System.out.println(puestobo.cargarPuestos().get(i).toString());
        }
    }
    private void cargarPuesto(){
        txtNombrePuesto.setText(puesto.getNombre());
        txtDescripcionPuesto.setText(puesto.getDescripcion());
        if(puesto.isActivo()){
            rdActivoPuesto.setSelected(true);
        }else if(!puesto.isActivo()){
            rdActivoPuesto.setSelected(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdActivoPuesto = new javax.swing.JRadioButton();
        lblNombrePuesto = new javax.swing.JLabel();
        txtNombrePuesto = new javax.swing.JTextField();
        lblDescripcionPuesto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionPuesto = new javax.swing.JTextArea();
        btnRegistrarPuesto = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblErrorPuesto = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdActivoPuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdActivoPuesto.setForeground(new java.awt.Color(255, 255, 255));
        rdActivoPuesto.setText("Activo");
        getContentPane().add(rdActivoPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        lblNombrePuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombrePuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePuesto.setText("Nombre:");
        getContentPane().add(lblNombrePuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        txtNombrePuesto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtNombrePuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, -1));

        lblDescripcionPuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDescripcionPuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionPuesto.setText("Descripción.");
        getContentPane().add(lblDescripcionPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        txtDescripcionPuesto.setColumns(20);
        txtDescripcionPuesto.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionPuesto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 260, 110));

        btnRegistrarPuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarPuesto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/registrar.png"))); // NOI18N
        btnRegistrarPuesto.setText("Registar");
        btnRegistrarPuesto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarPuesto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPuestoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgAtras.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 44, 28));

        lblErrorPuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorPuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorPuesto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorPuesto.setToolTipText("");
        getContentPane().add(lblErrorPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 580, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgRegistros.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnRegistrarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPuestoActionPerformed
        registrarPuesto();
    }//GEN-LAST:event_btnRegistrarPuestoActionPerformed
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        irAFrmRegistro();
    }//GEN-LAST:event_btnRegresarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPuesto dialog = new FrmPuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPuesto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcionPuesto;
    private javax.swing.JLabel lblErrorPuesto;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombrePuesto;
    private javax.swing.JRadioButton rdActivoPuesto;
    private javax.swing.JTextArea txtDescripcionPuesto;
    private javax.swing.JTextField txtNombrePuesto;
    // End of variables declaration//GEN-END:variables
}