/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiiprograhotelutn.gui.AgenciaDeViajes;
import proyectoiiprograhotelutn.bo.AgenciaDeViajesBO;
import proyectoiiprograhotelutn.entities.AgenciaDeViajes;
import proyectoiiprograhotelutn.entities.MiError;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** 28/11/2017
 **/
public class FrmAgenciaDeViajes extends javax.swing.JDialog {
    /**
     * Creates new form FrmTipoHabitacion
     */
    private AgenciaDeViajes agencia;
    public FrmAgenciaDeViajes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarAgencia.setContentAreaFilled(false);
        this.agencia = new AgenciaDeViajes();
        rdActivoPuesto.setVisible(false);
    }
    public FrmAgenciaDeViajes(java.awt.Frame parent, boolean modal, AgenciaDeViajes agencia) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarAgencia.setContentAreaFilled(false);
        btnRegistrarAgencia.setText("Editar");
        rdActivoPuesto.setContentAreaFilled(false);
        this.agencia = agencia;
        cargarAgencia();
    }
    private void irAFrmRegistro(){
        super.getParent().setVisible(true);
        dispose();
    } 
    public void registrarAgencia(){
        lblErrorAgencia.setText("");
        String telefono = txtTelefonoAgencia.getText().trim() + txtTelefonoAgencia2.getText().trim()
                + txtTelefonoAgencia3.getText().trim();
        try {
            AgenciaDeViajes agenciaNueva = new AgenciaDeViajes();
            agenciaNueva.setId(this.agencia.getId());
            agenciaNueva.setCodigo(txtCodigoAgencia.getText().trim().toUpperCase());
            agenciaNueva.setNombre(txtNombreAgencia.getText().trim());
            agenciaNueva.setTelefono(Integer.parseInt(telefono));
            agenciaNueva.setComision(sldPorcentajeComisionAgencia.getValue());
            if(!this.agencia.isActivo()){
                if(rdActivoPuesto.isSelected()){
                    agenciaNueva.setActivo(true);
                }else{
                    agenciaNueva.setActivo(false);
                }
            }
            AgenciaDeViajesBO agenciabo = new AgenciaDeViajesBO();
            if (agenciabo.registrarAgencia(agenciaNueva)) {
                lblErrorAgencia.setText("Agencia registrada con éxito.");
                super.getParent().setVisible(true);
                dispose();
            } else {
                lblErrorAgencia.setText("Intente nuevamente.");
            }
        } catch (MiError ex) {
            lblErrorAgencia.setText(ex.getMessage());
        } catch (Exception ex) {
            lblErrorAgencia.setText("Llamar a TI ...xD");
        }
    }
    public void cargarAgencias(){
        AgenciaDeViajesBO agenciabo = new AgenciaDeViajesBO();
        for (int i = 0; i < agenciabo.cargarAgencias().size(); i++) {
            System.out.println(agenciabo.cargarAgencias().get(i).toString());
        }
    }
    private void cargarAgencia(){
        txtCodigoAgencia.setText(agencia.getCodigo());
        txtNombreAgencia.setText(agencia.getNombre());
        String telefono = String.valueOf(agencia.getTelefono());
        for (int i = 0; i < 8; i++) {
            if(i <= 3){
                txtTelefonoAgencia.setText(txtTelefonoAgencia.getText() + String.valueOf(telefono.charAt(i)));
            }else if(i == 4 || i == 5){
                txtTelefonoAgencia2.setText(txtTelefonoAgencia2.getText() + String.valueOf(telefono.charAt(i)));
            }else if( i== 6 || i == 7){
                txtTelefonoAgencia3.setText(txtTelefonoAgencia3.getText() + String.valueOf(telefono.charAt(i)));
            }
        }
        sldPorcentajeComisionAgencia.setValue(agencia.getComision());
        if(agencia.isActivo()){
            rdActivoPuesto.setSelected(true);
        }else if(!agencia.isActivo()){
            rdActivoPuesto.setSelected(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdActivoPuesto = new javax.swing.JRadioButton();
        lblNombreAgencia = new javax.swing.JLabel();
        txtNombreAgencia = new javax.swing.JTextField();
        lblTelfonoAgencia = new javax.swing.JLabel();
        btnRegistrarAgencia = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblErrorAgencia = new javax.swing.JLabel();
        lblCodigoAgencia = new javax.swing.JLabel();
        txtCodigoAgencia = new javax.swing.JTextField();
        lblTelfonoAgencia1 = new javax.swing.JLabel();
        txtTelefonoAgencia3 = new javax.swing.JTextField();
        sldPorcentajeComisionAgencia = new javax.swing.JSlider();
        txtTelefonoAgencia = new javax.swing.JTextField();
        txtTelefonoAgencia2 = new javax.swing.JTextField();
        lblPorcentajeComision = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdActivoPuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdActivoPuesto.setForeground(new java.awt.Color(255, 255, 255));
        rdActivoPuesto.setText("Activo");
        getContentPane().add(rdActivoPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        lblNombreAgencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreAgencia.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreAgencia.setText("Nombre:");
        getContentPane().add(lblNombreAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txtNombreAgencia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtNombreAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 160, -1));

        lblTelfonoAgencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelfonoAgencia.setForeground(new java.awt.Color(255, 255, 255));
        lblTelfonoAgencia.setText("Telefono:");
        getContentPane().add(lblTelfonoAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        btnRegistrarAgencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarAgencia.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarAgencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/registrar.png"))); // NOI18N
        btnRegistrarAgencia.setText("Registar");
        btnRegistrarAgencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarAgencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAgenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgAtras.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 44, 28));

        lblErrorAgencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorAgencia.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorAgencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorAgencia.setToolTipText("");
        getContentPane().add(lblErrorAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 580, 30));

        lblCodigoAgencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigoAgencia.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoAgencia.setText("Código:");
        getContentPane().add(lblCodigoAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        txtCodigoAgencia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtCodigoAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 160, -1));

        lblTelfonoAgencia1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTelfonoAgencia1.setForeground(new java.awt.Color(255, 255, 255));
        lblTelfonoAgencia1.setText("Comisión:");
        getContentPane().add(lblTelfonoAgencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        txtTelefonoAgencia3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtTelefonoAgencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 40, -1));

        sldPorcentajeComisionAgencia.setBackground(new java.awt.Color(0, 102, 102));
        sldPorcentajeComisionAgencia.setForeground(new java.awt.Color(0, 102, 102));
        sldPorcentajeComisionAgencia.setMaximum(25);
        sldPorcentajeComisionAgencia.setPaintLabels(true);
        sldPorcentajeComisionAgencia.setValue(1);
        sldPorcentajeComisionAgencia.setValueIsAdjusting(true);
        sldPorcentajeComisionAgencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldPorcentajeComisionAgenciaStateChanged(evt);
            }
        });
        getContentPane().add(sldPorcentajeComisionAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        txtTelefonoAgencia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtTelefonoAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 50, -1));

        txtTelefonoAgencia2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtTelefonoAgencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 40, -1));

        lblPorcentajeComision.setBackground(new java.awt.Color(255, 255, 255));
        lblPorcentajeComision.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPorcentajeComision.setForeground(new java.awt.Color(255, 255, 255));
        lblPorcentajeComision.setText("%");
        getContentPane().add(lblPorcentajeComision, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 40, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 10, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 10, 10));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgRegistros.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnRegistrarAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAgenciaActionPerformed
        registrarAgencia();
    }//GEN-LAST:event_btnRegistrarAgenciaActionPerformed
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        irAFrmRegistro();
    }//GEN-LAST:event_btnRegresarActionPerformed
    private void sldPorcentajeComisionAgenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldPorcentajeComisionAgenciaStateChanged
        lblPorcentajeComision.setText(sldPorcentajeComisionAgencia.getValue() + "%");
    }//GEN-LAST:event_sldPorcentajeComisionAgenciaStateChanged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAgenciaDeViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAgenciaDeViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAgenciaDeViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAgenciaDeViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAgenciaDeViajes dialog = new FrmAgenciaDeViajes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarAgencia;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCodigoAgencia;
    private javax.swing.JLabel lblErrorAgencia;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombreAgencia;
    private javax.swing.JLabel lblPorcentajeComision;
    private javax.swing.JLabel lblTelfonoAgencia;
    private javax.swing.JLabel lblTelfonoAgencia1;
    private javax.swing.JRadioButton rdActivoPuesto;
    private javax.swing.JSlider sldPorcentajeComisionAgencia;
    private javax.swing.JTextField txtCodigoAgencia;
    private javax.swing.JTextField txtNombreAgencia;
    private javax.swing.JTextField txtTelefonoAgencia;
    private javax.swing.JTextField txtTelefonoAgencia2;
    private javax.swing.JTextField txtTelefonoAgencia3;
    // End of variables declaration//GEN-END:variables
}