/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiiprograhotelutn.gui.TiposHabitacion;
import proyectoiiprograhotelutn.bo.TipoHabitacionBO;
import proyectoiiprograhotelutn.entities.MiError;
import proyectoiiprograhotelutn.entities.TipoHabitacion;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** 01/11/2017
 **/
public class FrmTipoHabitacion extends javax.swing.JDialog {

    /**
     * Creates new form FrmTipoHabitacion
     */
    private TipoHabitacion tipo;
    public FrmTipoHabitacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarTipoHabitacion.setContentAreaFilled(false);
        this.tipo = new TipoHabitacion();
        rdActivoTipoHabitacion.setVisible(false);
    }
    public FrmTipoHabitacion(java.awt.Frame parent, boolean modal, TipoHabitacion tipo) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarTipoHabitacion.setContentAreaFilled(false);
        btnRegistrarTipoHabitacion.setText("Editar");
        rdActivoTipoHabitacion.setContentAreaFilled(false);
        this.tipo = tipo;
        cargarTipoHabitacion();
    }
    private void irAFrmRegistro(){
        super.getParent().setVisible(true);
        dispose();
    } 
    public void registrarTipoHabitacio(){
        lblErrorTipoHabitacion.setText("");
        try {
            TipoHabitacion tipoHabitacion = new TipoHabitacion();
            tipoHabitacion.setId(this.tipo.getId());
            tipoHabitacion.setCodigo(txtCodTipoHabitacion.getText().trim().toUpperCase());
            tipoHabitacion.setPrecio(Integer.parseInt(txtPrecioTipoHabitacion.getText().trim()));
            tipoHabitacion.setDescripcion(txtDescripcionTipoHabitacion.getText().trim());
            if(!this.tipo.isActivo()){
                if(rdActivoTipoHabitacion.isSelected()){
                    tipoHabitacion.setActivo(true);
                }else{
                    tipoHabitacion.setActivo(false);
                }
            }
            TipoHabitacionBO tipobo = new TipoHabitacionBO();
            if (tipobo.registrarTipoHabitacion(tipoHabitacion)) {
                lblErrorTipoHabitacion.setText("Tipo de habitación registrada con éxito.");
                super.getParent().setVisible(true);
                dispose();
            } else {
                lblErrorTipoHabitacion.setText("Intente nuevamente.");
            }
        } catch (MiError ex) {
            lblErrorTipoHabitacion.setText(ex.getMessage());
        } catch (Exception ex) {
            lblErrorTipoHabitacion.setText("Llamar a TI ...xD");
        }
    }
    public void cargarTiposDeHabitaciones(){
        TipoHabitacionBO tipobo = new TipoHabitacionBO();
        for (int i = 0; i < tipobo.cargarTiposDeHabitaciones().size(); i++) {
            System.out.println(tipobo.cargarTiposDeHabitaciones().get(i).toString());
        }
    }
    private void cargarTipoHabitacion(){
        txtCodTipoHabitacion.setText(tipo.getCodigo());
        txtPrecioTipoHabitacion.setText(String.valueOf(tipo.getPrecio()));
        txtDescripcionTipoHabitacion.setText(tipo.getDescripcion());
        if(tipo.isActivo()){
            rdActivoTipoHabitacion.setSelected(true);
        }else if(!tipo.isActivo()){
            rdActivoTipoHabitacion.setSelected(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdActivoTipoHabitacion = new javax.swing.JRadioButton();
        lblCodigoTipoHabitacion = new javax.swing.JLabel();
        txtCodTipoHabitacion = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecioTipoHabitacion = new javax.swing.JTextField();
        lblSimbloColones = new javax.swing.JLabel();
        lblDescripcionTipoHabitacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionTipoHabitacion = new javax.swing.JTextArea();
        btnRegistrarTipoHabitacion = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        lblErrorTipoHabitacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdActivoTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdActivoTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        rdActivoTipoHabitacion.setText("Activo");
        getContentPane().add(rdActivoTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        lblCodigoTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCodigoTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoTipoHabitacion.setText("Código: ");
        getContentPane().add(lblCodigoTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        txtCodTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtCodTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 160, -1));

        lblPrecio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio.setText("Precio:");
        getContentPane().add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtPrecioTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtPrecioTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 140, -1));

        lblSimbloColones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSimbloColones.setForeground(new java.awt.Color(255, 255, 255));
        lblSimbloColones.setText("₡");
        getContentPane().add(lblSimbloColones, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 20));

        lblDescripcionTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDescripcionTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcionTipoHabitacion.setText("Descripción.");
        getContentPane().add(lblDescripcionTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        txtDescripcionTipoHabitacion.setColumns(20);
        txtDescripcionTipoHabitacion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionTipoHabitacion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 260, 110));

        btnRegistrarTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegistrarTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarTipoHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/registrar.png"))); // NOI18N
        btnRegistrarTipoHabitacion.setText("Registar");
        btnRegistrarTipoHabitacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarTipoHabitacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTipoHabitacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgAtras.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 44, 28));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgRegistros.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        lblErrorTipoHabitacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorTipoHabitacion.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorTipoHabitacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorTipoHabitacion.setToolTipText("");
        getContentPane().add(lblErrorTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 580, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnRegistrarTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTipoHabitacionActionPerformed
        registrarTipoHabitacio();
    }//GEN-LAST:event_btnRegistrarTipoHabitacionActionPerformed
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        irAFrmRegistro();
    }//GEN-LAST:event_btnRegresarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTipoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTipoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTipoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTipoHabitacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmTipoHabitacion dialog = new FrmTipoHabitacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTipoHabitacion;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigoTipoHabitacion;
    private javax.swing.JLabel lblDescripcionTipoHabitacion;
    private javax.swing.JLabel lblErrorTipoHabitacion;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblSimbloColones;
    private javax.swing.JRadioButton rdActivoTipoHabitacion;
    private javax.swing.JTextField txtCodTipoHabitacion;
    private javax.swing.JTextArea txtDescripcionTipoHabitacion;
    private javax.swing.JTextField txtPrecioTipoHabitacion;
    // End of variables declaration//GEN-END:variables
}