/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiiprograhotelutn.gui.lugar;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import proyectoiiprograhotelutn.bo.CantonBO;
import proyectoiiprograhotelutn.bo.PaisBO;
import proyectoiiprograhotelutn.bo.ProvinciaBO;
import proyectoiiprograhotelutn.entities.Canton;
import proyectoiiprograhotelutn.entities.Distrito;
import proyectoiiprograhotelutn.entities.Lugar;
import proyectoiiprograhotelutn.entities.MiError;
import proyectoiiprograhotelutn.entities.Pais;
import proyectoiiprograhotelutn.entities.Provincia;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** 01/11/2017
 **/
public class FrmCanton extends javax.swing.JDialog {
    /**
     * Creates new form FrmTipoHabitacion
     */
    private Canton canton;
    private DefaultComboBoxModel<Pais> paises;
    private DefaultComboBoxModel<Provincia> provincias;
    public FrmCanton(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        paises = new DefaultComboBoxModel<>();
        provincias = new DefaultComboBoxModel<>();
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarCanton.setContentAreaFilled(false);
        this.canton = new Canton();
        cbxPais.setModel(paises);
        cbxProvincia.setModel(provincias);
        cargarPaises();
    }
    public FrmCanton(java.awt.Frame parent, boolean modal, Canton canton) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        paises = new DefaultComboBoxModel<>();
        provincias = new DefaultComboBoxModel<>();
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarCanton.setContentAreaFilled(false);
        this.canton = canton;
        cbxPais.setModel(paises);
        cbxProvincia.setModel(provincias);
    }
    /**
     * Se encarga de cragar paises en un combobox
     */
    public void cargarPaises(){
        cbxPais.removeAllItems();
        PaisBO paisbo = new PaisBO();
        ArrayList<Pais> listaPaises = paisbo.cargarPaises();
        for (Pais p : listaPaises) {
            paises.addElement(p);
        }
    }
    /**
     * Se encarga de cragar provincias en un combobox
     */
    public void cargarProvincias(){
        cbxProvincia.removeAllItems();
        ProvinciaBO provinciabo = new ProvinciaBO();
        ArrayList<Provincia> listaProvincias = provinciabo.cargarProvinciasDePais(((Pais) cbxPais.getSelectedItem()).getId());
        for (Provincia p : listaProvincias) {
            provincias.addElement(p);
        }
    }
    public void registrarCanton(){
        lblErrorCanton.setText("");
        try {
            canton.setId(this.canton.getId());
            Canton nuevoCanton = new Canton();
            nuevoCanton.setNombre(txtNombreCanton.getText().trim().toLowerCase());
            nuevoCanton.setProvincia((Provincia) cbxProvincia.getSelectedItem());
            CantonBO cantonbo = new CantonBO();
            if (cantonbo.registrarCanton(nuevoCanton)) {
                lblErrorCanton.setText("Cantón registrado con éxito.");
                txtNombreCanton.setText("");
            } else {
                lblErrorCanton.setText("Intente nuevamente.");
            }
        } catch (MiError ex) {
            lblErrorCanton.setText(ex.getMessage());
        } catch (Exception ex) {
            lblErrorCanton.setText("Llamar a TI ...xD");
        }
    }
    private void irAFrmRegistro(){
        super.getParent().setVisible(true);
        dispose();
    } 
    
//    private void cargarPais(){
//        txtNombrePais.setText(pais.getNombre());
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        lblErrorCanton = new javax.swing.JLabel();
        lblNombreCanton = new javax.swing.JLabel();
        txtNombreCanton = new javax.swing.JTextField();
        btnRegistrarCanton = new javax.swing.JButton();
        lblNombrePais = new javax.swing.JLabel();
        cbxPais = new javax.swing.JComboBox<>();
        lblNombreProvincia = new javax.swing.JLabel();
        cbxProvincia = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgAtras.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 44, 28));

        lblErrorCanton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorCanton.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorCanton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorCanton.setToolTipText("");
        getContentPane().add(lblErrorCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 580, 30));

        lblNombreCanton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreCanton.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCanton.setText("Nombre:");
        getContentPane().add(lblNombreCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        txtNombreCanton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtNombreCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 114, 29));

        btnRegistrarCanton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarCanton.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCanton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/registrar.png"))); // NOI18N
        btnRegistrarCanton.setText("Registar");
        btnRegistrarCanton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarCanton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCantonActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        lblNombrePais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombrePais.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePais.setText("Paises:");
        getContentPane().add(lblNombrePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 142, 28));

        lblNombreProvincia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreProvincia.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProvincia.setText("Provincias:");
        getContentPane().add(lblNombreProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        cbxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProvinciaActionPerformed(evt);
            }
        });
        getContentPane().add(cbxProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 142, 28));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgRegistros.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        irAFrmRegistro();
    }//GEN-LAST:event_btnRegresarActionPerformed
    private void btnRegistrarCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCantonActionPerformed
        registrarCanton();
    }//GEN-LAST:event_btnRegistrarCantonActionPerformed
    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        cargarProvincias();
    }//GEN-LAST:event_cbxPaisActionPerformed
    private void cbxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProvinciaActionPerformed
    }//GEN-LAST:event_cbxProvinciaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCanton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCanton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCanton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCanton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCanton dialog = new FrmCanton(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCanton;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Pais> cbxPais;
    private javax.swing.JComboBox<Provincia> cbxProvincia;
    private javax.swing.JLabel lblErrorCanton;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombreCanton;
    private javax.swing.JLabel lblNombrePais;
    private javax.swing.JLabel lblNombreProvincia;
    private javax.swing.JTextField txtNombreCanton;
    // End of variables declaration//GEN-END:variables
}