/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiiprograhotelutn.gui.Lugar;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import proyectoiiprograhotelutn.bo.CantonBO;
import proyectoiiprograhotelutn.bo.DistritoBO;
import proyectoiiprograhotelutn.bo.PaisBO;
import proyectoiiprograhotelutn.bo.ProvinciaBO;
import proyectoiiprograhotelutn.entities.Canton;
import proyectoiiprograhotelutn.entities.Distrito;
import proyectoiiprograhotelutn.entities.MiError;
import proyectoiiprograhotelutn.entities.Pais;
import proyectoiiprograhotelutn.entities.Provincia;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** 01/11/2017
 **/
public class FrmDistrito extends javax.swing.JDialog {
    /**
     * Creates new form FrmTipoHabitacion
     */
    private Distrito distrito;
    private DefaultComboBoxModel<Pais> paises;
    private DefaultComboBoxModel<Provincia> provincias;
    private DefaultComboBoxModel<Canton> cantones;
    public FrmDistrito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        paises = new DefaultComboBoxModel<>();
        provincias = new DefaultComboBoxModel<>();
        cantones = new DefaultComboBoxModel<>();
        btnRegresar.setContentAreaFilled(false);        
        btnRegistrarDistrito.setContentAreaFilled(false);   
        this.distrito = new Distrito();
        cbxPais.setModel(paises);
        cbxProvincia.setModel(provincias);
        cbxCanton.setModel(cantones);
        cargarPaises();
    }
    public FrmDistrito(java.awt.Frame parent, boolean modal, Distrito distrito) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        paises = new DefaultComboBoxModel<>();
        provincias = new DefaultComboBoxModel<>();
        cantones = new DefaultComboBoxModel<>();
        btnRegresar.setContentAreaFilled(false);        
        btnRegistrarDistrito.setContentAreaFilled(false);   
        cbxPais.setModel(paises);
        cbxProvincia.setModel(provincias);
        cbxCanton.setModel(cantones);
        this.distrito = distrito;
    }
    public void cargarPaises(){
        cbxPais.removeAllItems();
        PaisBO paisbo = new PaisBO();
        ArrayList<Pais> listaPaises = paisbo.cargarPaises();
        for (Pais p : listaPaises) {
            paises.addElement(p);
        }
    }
    public void cargarProvincias(){///Preguntar
        cbxProvincia.removeAllItems();
        ProvinciaBO provinciabo = new ProvinciaBO();
        ArrayList<Provincia> listaProvincias = provinciabo.cargarProvinciasDePais(((Pais) cbxPais.getSelectedItem()).getId());
        for (Provincia p : listaProvincias) {
            provincias.addElement(p);
        }
    }
    public void cargarCantones(int numberOfProvinces){///Preguntar
        cbxCanton.removeAllItems();
        if(numberOfProvinces > 0) {
            CantonBO cantonbo = new CantonBO();
            ArrayList<Canton> listaCantones = cantonbo.cargarCantonesDeProvincia(((Provincia) cbxProvincia.getSelectedItem()).getId());
            for (Canton c : listaCantones) {
                cantones.addElement(c);
            }
        }
    }
    public void registrarDistrito(){
        lblErrorDistrito.setText("");
        try {
            distrito.setId(this.distrito.getId());
            Distrito distritoNuevo = new Distrito();
            distritoNuevo.setNombre(txtNombreDistrito.getText().trim().toLowerCase());
            distritoNuevo.setCanton((Canton) cbxCanton.getSelectedItem());
            DistritoBO distritobo = new DistritoBO();
            if (distritobo.registrarDistrito(distritoNuevo)) {
                lblErrorDistrito.setText("Distrito registrado con éxito.");
            } else {
                lblErrorDistrito.setText("Intente nuevamente.");
            }
        } catch (MiError ex) {
            lblErrorDistrito.setText(ex.getMessage());
        } catch (Exception ex) {
            lblErrorDistrito.setText("Llamar a TI ...xD");
        }
    }
    private void irAFrmRegistro(){
        super.getParent().setVisible(true);
        dispose();
    } 
    
//    private void cargarPais(){
//        txtNombrePais.setText(pais.getNombre());
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        lblErrorDistrito = new javax.swing.JLabel();
        cbxCanton = new javax.swing.JComboBox<>();
        lblNombreDistrito = new javax.swing.JLabel();
        txtNombreDistrito = new javax.swing.JTextField();
        btnRegistrarDistrito = new javax.swing.JButton();
        lblNombrePais = new javax.swing.JLabel();
        cbxPais = new javax.swing.JComboBox<>();
        lblNombreProvincia = new javax.swing.JLabel();
        lblNombrePais1 = new javax.swing.JLabel();
        cbxProvincia = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgAtras.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 44, 28));

        lblErrorDistrito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorDistrito.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorDistrito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorDistrito.setToolTipText("");
        getContentPane().add(lblErrorDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 580, 30));

        getContentPane().add(cbxCanton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 140, 28));

        lblNombreDistrito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreDistrito.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreDistrito.setText("Nombre:");
        getContentPane().add(lblNombreDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        txtNombreDistrito.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtNombreDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 140, 29));

        btnRegistrarDistrito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarDistrito.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDistrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/registrar.png"))); // NOI18N
        btnRegistrarDistrito.setText("Registar");
        btnRegistrarDistrito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarDistrito.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarDistritoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        lblNombrePais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombrePais.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePais.setText("Paises:");
        getContentPane().add(lblNombrePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 142, 28));

        lblNombreProvincia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreProvincia.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProvincia.setText("Provincias:");
        getContentPane().add(lblNombreProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        lblNombrePais1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombrePais1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePais1.setText("Canton:");
        getContentPane().add(lblNombrePais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        cbxProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProvinciaActionPerformed(evt);
            }
        });
        getContentPane().add(cbxProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 142, 28));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgRegistros.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        irAFrmRegistro();
    }//GEN-LAST:event_btnRegresarActionPerformed
    private void btnRegistrarDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarDistritoActionPerformed
        registrarDistrito();
    }//GEN-LAST:event_btnRegistrarDistritoActionPerformed
    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        cargarProvincias();
    }//GEN-LAST:event_cbxPaisActionPerformed
    private void cbxProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProvinciaActionPerformed
        cargarCantones(cbxProvincia.getItemCount());
    }//GEN-LAST:event_cbxProvinciaActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDistrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDistrito dialog = new FrmDistrito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarDistrito;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Canton> cbxCanton;
    private javax.swing.JComboBox<Pais> cbxPais;
    private javax.swing.JComboBox<Provincia> cbxProvincia;
    private javax.swing.JLabel lblErrorDistrito;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombreDistrito;
    private javax.swing.JLabel lblNombrePais;
    private javax.swing.JLabel lblNombrePais1;
    private javax.swing.JLabel lblNombreProvincia;
    private javax.swing.JTextField txtNombreDistrito;
    // End of variables declaration//GEN-END:variables
}