/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiiprograhotelutn.gui.lugar;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import proyectoiiprograhotelutn.bo.PaisBO;
import proyectoiiprograhotelutn.bo.ProvinciaBO;
import proyectoiiprograhotelutn.entities.MiError;
import proyectoiiprograhotelutn.entities.Pais;
import proyectoiiprograhotelutn.entities.Provincia;
/**
 **
 ** @author Luis Alonso Corella Chaves
 ** 01/11/2017
 **/
public class FrmProvincia extends javax.swing.JDialog {
    /**
     * Creates new form FrmTipoHabitacion
     */
    private Provincia provincia;
    private DefaultComboBoxModel<Pais> paises;
    public FrmProvincia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        paises = new DefaultComboBoxModel<>();
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarProvincia.setContentAreaFilled(false);
        this.provincia = new Provincia();
        cbxPais.setModel(paises);
        cargarPaises();
    }
    public FrmProvincia(java.awt.Frame parent, boolean modal, Provincia provincia) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        paises = new DefaultComboBoxModel<>();
        btnRegresar.setContentAreaFilled(false);
        btnRegistrarProvincia.setContentAreaFilled(false);
        this.provincia = provincia;
    }
    private void irAFrmRegistro(){
        super.getParent().setVisible(true);
        dispose();
    }
    public void cargarPaises(){
        cbxPais.removeAllItems();
        PaisBO paisbo = new PaisBO();
        ArrayList<Pais> listaPaises = paisbo.cargarPaises();
        for (Pais p : listaPaises) {
            paises.addElement(p);
        }
    }
    public void registrarProvincia(){
        lblErrorLugar.setText("");
        try {
            provincia.setId(this.provincia.getId());
            Provincia nuevaProvincia = new Provincia();
            nuevaProvincia.setNombre(txtNombreProvincia.getText().trim().toLowerCase());
            nuevaProvincia.setPais((Pais) cbxPais.getSelectedItem());
            ProvinciaBO provinciabo = new ProvinciaBO();
            if (provinciabo.registrarProvincia(nuevaProvincia)) {
                lblErrorLugar.setText("Provincia registrada con éxito.");
            } else {
                lblErrorLugar.setText("Intente nuevamente.");
            }
        } catch (MiError ex) {
            lblErrorLugar.setText(ex.getMessage());
        } catch (Exception ex) {
            lblErrorLugar.setText("Llamar a TI ...xD");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresar = new javax.swing.JButton();
        lblErrorLugar = new javax.swing.JLabel();
        cbxPais = new javax.swing.JComboBox<>();
        lblNombrePais = new javax.swing.JLabel();
        txtNombreProvincia = new javax.swing.JTextField();
        btnRegistrarProvincia = new javax.swing.JButton();
        lblNombreProvincia = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgAtras.png"))); // NOI18N
        btnRegresar.setOpaque(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 44, 28));

        lblErrorLugar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorLugar.setForeground(new java.awt.Color(255, 255, 255));
        lblErrorLugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorLugar.setToolTipText("");
        getContentPane().add(lblErrorLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 580, 30));

        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 142, 28));

        lblNombrePais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombrePais.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePais.setText("Pais:");
        getContentPane().add(lblNombrePais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        txtNombreProvincia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(txtNombreProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 29));

        btnRegistrarProvincia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrarProvincia.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProvincia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/registrar.png"))); // NOI18N
        btnRegistrarProvincia.setText("Registar");
        btnRegistrarProvincia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrarProvincia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistrarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProvinciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        lblNombreProvincia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNombreProvincia.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProvincia.setText("Nombre:");
        getContentPane().add(lblNombreProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoiiprograhotelutn/img/imgRegistros.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        irAFrmRegistro();
    }//GEN-LAST:event_btnRegresarActionPerformed
    private void btnRegistrarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProvinciaActionPerformed
        registrarProvincia();
    }//GEN-LAST:event_btnRegistrarProvinciaActionPerformed
    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProvincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProvincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProvincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProvincia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmProvincia dialog = new FrmProvincia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarProvincia;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Pais> cbxPais;
    private javax.swing.JLabel lblErrorLugar;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombrePais;
    private javax.swing.JLabel lblNombreProvincia;
    private javax.swing.JTextField txtNombreProvincia;
    // End of variables declaration//GEN-END:variables
}